---
- name: Add ESXi Host to vCenter
  hosts: localhost
  gather_facts: false
  connection: Vcenter

  tasks:
  - name : Add ESXi Host to vCenter
    local_action:
      module: vmware_host
      hostname: '192.168.23.9'
      username: 'administrator@vsphere.local'
      password: 'vmware'
      validate_certs: no
      datacenter_name: KAMEL.SEBBANE
      cluster_name: TEDDY.FRONTIN
      esxi_hostname: '192.168.23.10'
      esxi_username: 'root'
      esxi_password: 'Espoir15'
      state: present
