---
- name : Automatize vmware
  hosts: localhost

  tasks:
  - name: Create VM
    local_action:
      module: vmware_guest
      hostname: 192.168.23.9
      username: administrator@vsphere.local
      password: vmware
      validate_certs: no
      name: test.ansible
      state: poweredoff
      folder: /
      datacenter: JEREMY.PRADEL
      guest_id: centos64Guest
      disk:
      - size_gb: "10"
        type: thin
        datastore: datastore1
      networks:
      - name: VM Network
        type: dhcp
      hardware:
        memory_mb: "512"
        num_cpus: "1"
        scsi: paravirtual
        hotadd_cpu: True
        hotremove_cpu: True
        hotadd_memory: False
    tags: vm
