---
- name : Automatize vmware
  hosts: localhost

  tasks:
  - name: Create VM
    local_action:
      module: vmware_guest
      hostname: 192.168.1.48
      username: root
      password: Root1234!
      validate_certs: no
      name: VM_test
      state: poweredoff
      disk:
      - size_gb: "10"
        type: thin
        datastore: stockage
      networks:
      - name: VM Network
        type: dhcp
      hardware:
        memory_mb: "512"
        num_cpus: "1"
        scsi: paravirtual
        hotadd_cpu: True
        hotremove_cpu: True
        hotadd_memory: False
    tags: vm
