---
- name : Create Datacenter
  hosts: Vcenter
  gather_facts: false
  connection: Vcenter

  tasks:
  - name: Create Datacenter
    local_action:
      module: vmware_datacenter
      hostname: 192.168.23.9
      username: administrator@vsphere.local
      password: vmware
      datacenter_name: 'vDc_ESGI'
      state: present
      validate_certs: no
#    delegate_to: localhost
#    register: vmfacts
