---
- name : Create Cluster
  hosts: localhost
  gather_facts: false
  connection: Vcenter


  tasks:
  - name: Create Cluster
    local_action:
      module: vmware_cluster
      hostname: 192.168.23.9
      username: administrator@vsphere.local
      password: vmware
      datacenter_name: 'vDc_ESGI'
      cluster_name: Cluster_ESGI
      enable_ha: yes
      enable_drs: yes
      enable_vsan: no
      validate_certs: no
#    delegate_to: localhost
#    register: vmfacts
