---
- name: Backup ESXi
  hosts: localhost
  gather_facts: false
  connection: Vcenter

  tasks:
  - name: ESXI backup test
    local_action:
      module: vmware_cfg_backup
      hostname: vCenter
      esxi_hostname: 192.168.23.11
      username: administrator@vsphere.local
      password: vmware
      validate_certs: no
      state: saved
      dest: /tmp/
