---
- name: Backup ESXi
  hosts: localhost
  gather_facts: false
  connection: Vcenter
  
  vars_prompt:
    - name: "user"
      prompt: "utilisateur Vcenter"
    - name: "password"
      prompt: "password Vcenter"
      private: yes

  tasks:
  - name: ESXI backup test
    local_action:
      module: vmware_cfg_backup
      hostname: vCenter
      esxi_hostname: 192.168.23.11
      username: "{{ user }}"
      password: "{{ password }}"
      validate_certs: no
      state: saved
      dest: /tmp/
